coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
  flags:
    go:
      paths:
        - packages/
        - services/
