coverage:
  status:
    project:
      default:
        target: 94%
        threshold: 1%
    patch:
      default:
        target: 80%
  ignore:
    - "packages/proto/gen/go/**"
  flags:
    go:
      paths:
        - packages/
        - services/
