name: Tagged Release Docker

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

concurrency:
  group: tagged-release-docker-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  tagged-docker-publish:
    name: tagged-docker-publish
    permissions:
      packages: write
      id-token: write
      attestations: write
      security-events: write
      contents: read
    secrets: inherit
    uses: ./.github/workflows/docker-publish.yml
    with:
      image_tag: ${{ github.ref_name }}
